// <auto-generated />
using System;
using FonRadar.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FonRadar.DataAccess.Migrations
{
    [DbContext(typeof(FonRadarContext))]
    partial class FonRadarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FonRadar.Entities.Invoice", b =>
                {
                    b.Property<int>("invoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("invoiceId"));

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("buyerTaxId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("invoiceCost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("invoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("supplierTaxId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("termDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("invoiceId");

                    b.ToTable("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
