version: '2'

services:
  web:
    build:
      context: ../  # Ana dizin
      dockerfile: FonRadar.WebApi/Dockerfile  # Dockerfile'ın yolu
    ports:
      - "8001:80"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: FonRadarDb
    ports:
      - "6432:5432"
